////////////////////////////////////////////////////////////////////////// <!--
/// Copyright (C) 2014-2018 Frontier (fr0nt13r789@gmail.com)           ///
///                                                                    ///
/// Flib is licensed under the terms of GNU GPL.                       ///
/// Therefore you may freely use it in your project,                   ///
/// modify it, redistribute it without any warranty on the             ///
/// condition that this disclaimer is not modified/removed.            ///
/// You may not misclaim the origin of this software.                  ///
///                                                                    ///
/// If you use this software in your program/project a                 ///
/// note about it and an email for the author (fr0nt13r789@gmail.com)  ///
/// is not required but highly appreciated.                            ///
///                                                                    ///
/// You should have received a copy of GNU GPL with this software      ///
///                                                                    ///
////////////////////////////////////////////////////////////////////////// -->
#ifndef FRONTIER_GL_FUNCTIONS_H_INCLUDED
#define FRONTIER_GL_FUNCTIONS_H_INCLUDED
#include <FRONTIER/System/util/API.h>
#include <FRONTIER/GL/GL_API_ENTRY.h>
#include <FRONTIER/GL/GL_TYPES.hpp>

namespace fg
{
	namespace gl
	{
		FRONTIER_API void (API_ENTRY *getGlFuncPtr(int index))();

		template<class R,class... ArgTypes>
		inline R (API_ENTRY *getGlFuncPtr(int index))(ArgTypes... args)
		{
			typedef R (API_ENTRY *GlFuncType)(ArgTypes... args);
			return (GlFuncType)(getGlFuncPtr(index));
		}
	}
}

#define glAccum (fg::gl::getGlFuncPtr<void,GLenum,GLfloat>(0))
#define glActiveShaderProgram (fg::gl::getGlFuncPtr<void,GLuint,GLuint>(1))
#define glActiveTexture (fg::gl::getGlFuncPtr<void,GLenum>(2))
#define glAlphaFunc (fg::gl::getGlFuncPtr<void,GLenum,GLfloat>(3))
#define glAreTexturesResident (fg::gl::getGlFuncPtr<GLboolean,GLsizei,const GLuint*,GLboolean*>(4))
#define glArrayElement (fg::gl::getGlFuncPtr<void,GLint>(5))
#define glAttachObjectARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLhandleARB>(6))
#define glAttachShader (fg::gl::getGlFuncPtr<void,GLuint,GLuint>(7))
#define glBegin (fg::gl::getGlFuncPtr<void,GLenum>(8))
#define glBeginConditionalRender (fg::gl::getGlFuncPtr<void,GLuint,GLenum>(9))
#define glBeginQuery (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(10))
#define glBeginQueryIndexed (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLuint>(11))
#define glBeginTransformFeedback (fg::gl::getGlFuncPtr<void,GLenum>(12))
#define glBindAttribLocation (fg::gl::getGlFuncPtr<void,GLuint,GLuint,const GLchar*>(13))
#define glBindAttribLocationARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLuint,const GLcharARB*>(14))
#define glBindBuffer (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(15))
#define glBindBufferARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(16))
#define glBindBufferBase (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLuint>(17))
#define glBindBufferRange (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLuint,GLintptr,GLsizeiptr>(18))
#define glBindFragDataLocation (fg::gl::getGlFuncPtr<void,GLuint,GLuint,const GLchar*>(19))
#define glBindFragDataLocationIndexed (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLuint,const GLchar*>(20))
#define glBindFramebuffer (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(21))
#define glBindFramebufferEXT (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(22))
#define glBindImageTexture (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLint,GLboolean,GLint,GLenum,GLenum>(23))
#define glBindProgramARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(24))
#define glBindProgramPipeline (fg::gl::getGlFuncPtr<void,GLuint>(25))
#define glBindRenderbuffer (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(26))
#define glBindRenderbufferEXT (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(27))
#define glBindSampler (fg::gl::getGlFuncPtr<void,GLuint,GLuint>(28))
#define glBindTexture (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(29))
#define glBindTransformFeedback (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(30))
#define glBindVertexArray (fg::gl::getGlFuncPtr<void,GLuint>(31))
#define glBitmap (fg::gl::getGlFuncPtr<void,GLsizei,GLsizei,GLfloat,GLfloat,GLfloat,GLfloat,const GLubyte*>(32))
#define glBlendColor (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat,GLfloat>(33))
#define glBlendEquation (fg::gl::getGlFuncPtr<void,GLenum>(34))
#define glBlendEquationSeparate (fg::gl::getGlFuncPtr<void,GLenum,GLenum>(35))
#define glBlendEquationSeparatei (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLenum>(36))
#define glBlendEquationi (fg::gl::getGlFuncPtr<void,GLuint,GLenum>(37))
#define glBlendFunc (fg::gl::getGlFuncPtr<void,GLenum,GLenum>(38))
#define glBlendFuncSeparate (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLenum>(39))
#define glBlendFuncSeparatei (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLenum,GLenum,GLenum>(40))
#define glBlendFunci (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLenum>(41))
#define glBlitFramebuffer (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint,GLint,GLint,GLint,GLint,GLint,GLbitfield,GLenum>(42))
#define glBufferData (fg::gl::getGlFuncPtr<void,GLenum,GLsizeiptr,const GLvoid*,GLenum>(43))
#define glBufferDataARB (fg::gl::getGlFuncPtr<void,GLenum,GLsizeiptrARB,const GLvoid*,GLenum>(44))
#define glBufferSubData (fg::gl::getGlFuncPtr<void,GLenum,GLintptr,GLsizeiptr,const GLvoid*>(45))
#define glBufferSubDataARB (fg::gl::getGlFuncPtr<void,GLenum,GLintptrARB,GLsizeiptrARB,const GLvoid*>(46))
#define glCallList (fg::gl::getGlFuncPtr<void,GLuint>(47))
#define glCallLists (fg::gl::getGlFuncPtr<void,GLsizei,GLenum,const GLvoid*>(48))
#define glCheckFramebufferStatus (fg::gl::getGlFuncPtr<GLenum,GLenum>(49))
#define glCheckFramebufferStatusEXT (fg::gl::getGlFuncPtr<GLenum,GLenum>(50))
#define glClampColor (fg::gl::getGlFuncPtr<void,GLenum,GLenum>(51))
#define glClear (fg::gl::getGlFuncPtr<void,GLbitfield>(52))
#define glClearAccum (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat,GLfloat>(53))
#define glClearBufferfi (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLfloat,GLint>(54))
#define glClearBufferfv (fg::gl::getGlFuncPtr<void,GLenum,GLint,const GLfloat*>(55))
#define glClearBufferiv (fg::gl::getGlFuncPtr<void,GLenum,GLint,const GLint*>(56))
#define glClearBufferuiv (fg::gl::getGlFuncPtr<void,GLenum,GLint,const GLuint*>(57))
#define glClearColor (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat,GLfloat>(58))
#define glClearDepth (fg::gl::getGlFuncPtr<void,GLdouble>(59))
#define glClearDepthf (fg::gl::getGlFuncPtr<void,GLfloat>(60))
#define glClearIndex (fg::gl::getGlFuncPtr<void,GLfloat>(61))
#define glClearStencil (fg::gl::getGlFuncPtr<void,GLint>(62))
#define glClientActiveTexture (fg::gl::getGlFuncPtr<void,GLenum>(63))
#define glClientWaitSync (fg::gl::getGlFuncPtr<GLenum,GLsync,GLbitfield,GLuint64>(64))
#define glClipPlane (fg::gl::getGlFuncPtr<void,GLenum,const GLdouble*>(65))
#define glColor3b (fg::gl::getGlFuncPtr<void,GLbyte,GLbyte,GLbyte>(66))
#define glColor3bv (fg::gl::getGlFuncPtr<void,const GLbyte*>(67))
#define glColor3d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble>(68))
#define glColor3dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(69))
#define glColor3f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat>(70))
#define glColor3fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(71))
#define glColor3i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint>(72))
#define glColor3iv (fg::gl::getGlFuncPtr<void,const GLint*>(73))
#define glColor3s (fg::gl::getGlFuncPtr<void,GLshort,GLshort,GLshort>(74))
#define glColor3sv (fg::gl::getGlFuncPtr<void,const GLshort*>(75))
#define glColor3ub (fg::gl::getGlFuncPtr<void,GLubyte,GLubyte,GLubyte>(76))
#define glColor3ubv (fg::gl::getGlFuncPtr<void,const GLubyte*>(77))
#define glColor3ui (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLuint>(78))
#define glColor3uiv (fg::gl::getGlFuncPtr<void,const GLuint*>(79))
#define glColor3us (fg::gl::getGlFuncPtr<void,GLushort,GLushort,GLushort>(80))
#define glColor3usv (fg::gl::getGlFuncPtr<void,const GLushort*>(81))
#define glColor4b (fg::gl::getGlFuncPtr<void,GLbyte,GLbyte,GLbyte,GLbyte>(82))
#define glColor4bv (fg::gl::getGlFuncPtr<void,const GLbyte*>(83))
#define glColor4d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble,GLdouble>(84))
#define glColor4dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(85))
#define glColor4f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat,GLfloat>(86))
#define glColor4fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(87))
#define glColor4i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint,GLint>(88))
#define glColor4iv (fg::gl::getGlFuncPtr<void,const GLint*>(89))
#define glColor4s (fg::gl::getGlFuncPtr<void,GLshort,GLshort,GLshort,GLshort>(90))
#define glColor4sv (fg::gl::getGlFuncPtr<void,const GLshort*>(91))
#define glColor4ub (fg::gl::getGlFuncPtr<void,GLubyte,GLubyte,GLubyte,GLubyte>(92))
#define glColor4ubv (fg::gl::getGlFuncPtr<void,const GLubyte*>(93))
#define glColor4ui (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLuint,GLuint>(94))
#define glColor4uiv (fg::gl::getGlFuncPtr<void,const GLuint*>(95))
#define glColor4us (fg::gl::getGlFuncPtr<void,GLushort,GLushort,GLushort,GLushort>(96))
#define glColor4usv (fg::gl::getGlFuncPtr<void,const GLushort*>(97))
#define glColorMask (fg::gl::getGlFuncPtr<void,GLboolean,GLboolean,GLboolean,GLboolean>(98))
#define glColorMaski (fg::gl::getGlFuncPtr<void,GLuint,GLboolean,GLboolean,GLboolean,GLboolean>(99))
#define glColorMaterial (fg::gl::getGlFuncPtr<void,GLenum,GLenum>(100))
#define glColorP3ui (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(101))
#define glColorP3uiv (fg::gl::getGlFuncPtr<void,GLenum,const GLuint*>(102))
#define glColorP4ui (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(103))
#define glColorP4uiv (fg::gl::getGlFuncPtr<void,GLenum,const GLuint*>(104))
#define glColorPointer (fg::gl::getGlFuncPtr<void,GLint,GLenum,GLsizei,const GLvoid*>(105))
#define glCompileShader (fg::gl::getGlFuncPtr<void,GLuint>(106))
#define glCompileShaderARB (fg::gl::getGlFuncPtr<void,GLhandleARB>(107))
#define glCompressedTexImage1D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLenum,GLsizei,GLint,GLsizei,const GLvoid*>(108))
#define glCompressedTexImage2D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLenum,GLsizei,GLsizei,GLint,GLsizei,const GLvoid*>(109))
#define glCompressedTexImage3D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLenum,GLsizei,GLsizei,GLsizei,GLint,GLsizei,const GLvoid*>(110))
#define glCompressedTexSubImage1D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLsizei,GLenum,GLsizei,const GLvoid*>(111))
#define glCompressedTexSubImage2D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLint,GLsizei,GLsizei,GLenum,GLsizei,const GLvoid*>(112))
#define glCompressedTexSubImage3D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLint,GLint,GLsizei,GLsizei,GLsizei,GLenum,GLsizei,const GLvoid*>(113))
#define glCopyBufferSubData (fg::gl::getGlFuncPtr<void *,GLenum,GLenum,GLintptr,GLintptr,GLsizeiptr>(114))
#define glCopyPixels (fg::gl::getGlFuncPtr<void,GLint,GLint,GLsizei,GLsizei,GLenum>(115))
#define glCopyTexImage1D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLenum,GLint,GLint,GLsizei,GLint>(116))
#define glCopyTexImage2D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLenum,GLint,GLint,GLsizei,GLsizei,GLint>(117))
#define glCopyTexSubImage1D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLint,GLint,GLsizei>(118))
#define glCopyTexSubImage2D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLint,GLint,GLint,GLsizei,GLsizei>(119))
#define glCopyTexSubImage3D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLint,GLint,GLint,GLint,GLsizei,GLsizei>(120))
#define glCreateProgram (fg::gl::getGlFuncPtr<GLuint>(121))
#define glCreateProgramObjectARB (fg::gl::getGlFuncPtr<GLhandleARB>(122))
#define glCreateShader (fg::gl::getGlFuncPtr<GLuint,GLenum>(123))
#define glCreateShaderObjectARB (fg::gl::getGlFuncPtr<GLhandleARB,GLenum>(124))
#define glCreateShaderProgramv (fg::gl::getGlFuncPtr<GLuint,GLenum,GLsizei,const GLchar*const*>(125))
#define glCullFace (fg::gl::getGlFuncPtr<void,GLenum>(126))
#define glDeleteBuffers (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(127))
#define glDeleteBuffersARB (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(128))
#define glDeleteFramebuffers (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(129))
#define glDeleteFramebuffersEXT (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(130))
#define glDeleteLists (fg::gl::getGlFuncPtr<void,GLuint,GLsizei>(131))
#define glDeleteObjectARB (fg::gl::getGlFuncPtr<void,GLhandleARB>(132))
#define glDeleteProgram (fg::gl::getGlFuncPtr<void,GLuint>(133))
#define glDeleteProgramPipelines (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(134))
#define glDeleteProgramsARB (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(135))
#define glDeleteQueries (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(136))
#define glDeleteRenderbuffers (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(137))
#define glDeleteRenderbuffersEXT (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(138))
#define glDeleteSamplers (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(139))
#define glDeleteShader (fg::gl::getGlFuncPtr<void,GLuint>(140))
#define glDeleteSync (fg::gl::getGlFuncPtr<void,GLsync>(141))
#define glDeleteTextures (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(142))
#define glDeleteTransformFeedbacks (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(143))
#define glDeleteVertexArrays (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*>(144))
#define glDepthFunc (fg::gl::getGlFuncPtr<void,GLenum>(145))
#define glDepthMask (fg::gl::getGlFuncPtr<void,GLboolean>(146))
#define glDepthRange (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble>(147))
#define glDepthRangeArrayv (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,const GLdouble*>(148))
#define glDepthRangeIndexed (fg::gl::getGlFuncPtr<void,GLuint,GLdouble,GLdouble>(149))
#define glDepthRangef (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat>(150))
#define glDetachObjectARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLhandleARB>(151))
#define glDetachShader (fg::gl::getGlFuncPtr<void,GLuint,GLuint>(152))
#define glDisable (fg::gl::getGlFuncPtr<void,GLenum>(153))
#define glDisableClientState (fg::gl::getGlFuncPtr<void,GLenum>(154))
#define glDisableVertexAttribArray (fg::gl::getGlFuncPtr<void,GLuint>(155))
#define glDisableVertexAttribArrayARB (fg::gl::getGlFuncPtr<void,GLuint>(156))
#define glDisablei (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(157))
#define glDispatchCompute (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLuint>(158))
#define glDispatchComputeIndirect (fg::gl::getGlFuncPtr<void,GLintptr>(159))
#define glDrawArrays (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLsizei>(160))
#define glDrawArraysIndirect (fg::gl::getGlFuncPtr<void,GLenum,const GLvoid*>(161))
#define glDrawArraysInstanced (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLsizei,GLsizei>(162))
#define glDrawArraysInstancedBaseInstance (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLsizei,GLsizei,GLuint>(163))
#define glDrawBuffer (fg::gl::getGlFuncPtr<void,GLenum>(164))
#define glDrawBuffers (fg::gl::getGlFuncPtr<void,GLsizei,const GLenum*>(165))
#define glDrawElements (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,GLenum,const GLvoid*>(166))
#define glDrawElementsBaseVertex (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,GLenum,const GLvoid*,GLint>(167))
#define glDrawElementsIndirect (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLvoid*>(168))
#define glDrawElementsInstanced (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,GLenum,const GLvoid*,GLsizei>(169))
#define glDrawElementsInstancedBaseInstance (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,GLenum,const GLvoid*,GLsizei,GLuint>(170))
#define glDrawElementsInstancedBaseVertex (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,GLenum,const GLvoid*,GLsizei,GLint>(171))
#define glDrawElementsInstancedBaseVertexBaseInstance (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,GLenum,const GLvoid*,GLsizei,GLint,GLuint>(172))
#define glDrawPixels (fg::gl::getGlFuncPtr<void,GLsizei,GLsizei,GLenum,GLenum,const GLvoid*>(173))
#define glDrawRangeElements (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLuint,GLsizei,GLenum,const GLvoid*>(174))
#define glDrawRangeElementsBaseVertex (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLuint,GLsizei,GLenum,const GLvoid*,GLint>(175))
#define glDrawTransformFeedback (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(176))
#define glDrawTransformFeedbackInstanced (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLsizei>(177))
#define glDrawTransformFeedbackStream (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLuint>(178))
#define glDrawTransformFeedbackStreamInstanced (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLuint,GLsizei>(179))
#define glEdgeFlag (fg::gl::getGlFuncPtr<void,GLboolean>(180))
#define glEdgeFlagPointer (fg::gl::getGlFuncPtr<void,GLsizei,const GLvoid*>(181))
#define glEdgeFlagv (fg::gl::getGlFuncPtr<void,const GLboolean*>(182))
#define glEnable (fg::gl::getGlFuncPtr<void,GLenum>(183))
#define glEnableClientState (fg::gl::getGlFuncPtr<void,GLenum>(184))
#define glEnableVertexAttribArray (fg::gl::getGlFuncPtr<void,GLuint>(185))
#define glEnableVertexAttribArrayARB (fg::gl::getGlFuncPtr<void,GLuint>(186))
#define glEnablei (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(187))
#define glEnd (fg::gl::getGlFuncPtr<void>(188))
#define glEndConditionalRender (fg::gl::getGlFuncPtr<void>(189))
#define glEndList (fg::gl::getGlFuncPtr<void>(190))
#define glEndQuery (fg::gl::getGlFuncPtr<void,GLenum>(191))
#define glEndQueryIndexed (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(192))
#define glEndTransformFeedback (fg::gl::getGlFuncPtr<void>(193))
#define glEvalCoord1d (fg::gl::getGlFuncPtr<void,GLdouble>(194))
#define glEvalCoord1dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(195))
#define glEvalCoord1f (fg::gl::getGlFuncPtr<void,GLfloat>(196))
#define glEvalCoord1fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(197))
#define glEvalCoord2d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble>(198))
#define glEvalCoord2dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(199))
#define glEvalCoord2f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat>(200))
#define glEvalCoord2fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(201))
#define glEvalMesh1 (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint>(202))
#define glEvalMesh2 (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLint,GLint>(203))
#define glEvalPoint1 (fg::gl::getGlFuncPtr<void,GLint>(204))
#define glEvalPoint2 (fg::gl::getGlFuncPtr<void,GLint,GLint>(205))
#define glFeedbackBuffer (fg::gl::getGlFuncPtr<void,GLsizei,GLenum,GLfloat*>(206))
#define glFenceSync (fg::gl::getGlFuncPtr<GLsync,GLenum,GLbitfield>(207))
#define glFinish (fg::gl::getGlFuncPtr<void>(208))
#define glFlush (fg::gl::getGlFuncPtr<void>(209))
#define glFlushMappedBufferRange (fg::gl::getGlFuncPtr<void,GLenum,GLintptr,GLsizeiptr>(210))
#define glFogCoordPointer (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,const GLvoid*>(211))
#define glFogCoordd (fg::gl::getGlFuncPtr<void,GLdouble>(212))
#define glFogCoorddv (fg::gl::getGlFuncPtr<void,const GLdouble*>(213))
#define glFogCoordf (fg::gl::getGlFuncPtr<void,GLfloat>(214))
#define glFogCoordfv (fg::gl::getGlFuncPtr<void,const GLfloat*>(215))
#define glFogf (fg::gl::getGlFuncPtr<void,GLenum,GLfloat>(216))
#define glFogfv (fg::gl::getGlFuncPtr<void,GLenum,const GLfloat*>(217))
#define glFogi (fg::gl::getGlFuncPtr<void,GLenum,GLint>(218))
#define glFogiv (fg::gl::getGlFuncPtr<void,GLenum,const GLint*>(219))
#define glFramebufferRenderbuffer (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLuint>(220))
#define glFramebufferRenderbufferEXT (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLuint>(221))
#define glFramebufferTexture (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLuint,GLint>(222))
#define glFramebufferTexture1D (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLuint,GLint>(223))
#define glFramebufferTexture1DEXT (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLuint,GLint>(224))
#define glFramebufferTexture2D (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLuint,GLint>(225))
#define glFramebufferTexture2DEXT (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLuint,GLint>(226))
#define glFramebufferTexture3D (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLuint,GLint,GLint>(227))
#define glFramebufferTexture3DEXT (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLuint,GLint,GLint>(228))
#define glFramebufferTextureLayer (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLuint,GLint,GLint>(229))
#define glFrontFace (fg::gl::getGlFuncPtr<void,GLenum>(230))
#define glFrustum (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble,GLdouble,GLdouble,GLdouble>(231))
#define glGenBuffers (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(232))
#define glGenBuffersARB (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(233))
#define glGenFramebuffers (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(234))
#define glGenFramebuffersEXT (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(235))
#define glGenLists (fg::gl::getGlFuncPtr<GLuint,GLsizei>(236))
#define glGenProgramPipelines (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(237))
#define glGenProgramsARB (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(238))
#define glGenQueries (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(239))
#define glGenRenderbuffers (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(240))
#define glGenRenderbuffersEXT (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(241))
#define glGenSamplers (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(242))
#define glGenTextures (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(243))
#define glGenTransformFeedbacks (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(244))
#define glGenVertexArrays (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(245))
#define glGenerateMipmap (fg::gl::getGlFuncPtr<void,GLenum>(246))
#define glGenerateMipmapEXT (fg::gl::getGlFuncPtr<void,GLenum>(247))
#define glGetActiveAtomicCounterBufferiv (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLenum,GLint*>(248))
#define glGetActiveAttrib (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLsizei,GLsizei*,GLint*,GLenum*,GLchar*>(249))
#define glGetActiveAttribARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLuint,GLsizei,GLsizei*,GLint*,GLenum*,GLcharARB*>(250))
#define glGetActiveSubroutineName (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLuint,GLsizei,GLsizei*,GLchar*>(251))
#define glGetActiveSubroutineUniformName (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLuint,GLsizei,GLsizei*,GLchar*>(252))
#define glGetActiveSubroutineUniformiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLuint,GLenum,GLint*>(253))
#define glGetActiveUniform (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLsizei,GLsizei*,GLint*,GLenum*,GLchar*>(254))
#define glGetActiveUniformARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLuint,GLsizei,GLsizei*,GLint*,GLenum*,GLcharARB*>(255))
#define glGetActiveUniformBlockName (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLsizei,GLsizei*,GLchar*>(256))
#define glGetActiveUniformBlockiv (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLenum,GLint*>(257))
#define glGetActiveUniformName (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLsizei,GLsizei*,GLchar*>(258))
#define glGetActiveUniformsiv (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,const GLuint*,GLenum,GLint*>(259))
#define glGetAttachedObjectsARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLsizei,GLsizei*,GLhandleARB*>(260))
#define glGetAttachedShaders (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,GLsizei*,GLuint*>(261))
#define glGetAttribLocation (fg::gl::getGlFuncPtr<GLint,GLuint,const GLchar*>(262))
#define glGetAttribLocationARB (fg::gl::getGlFuncPtr<GLint,GLhandleARB,const GLcharARB*>(263))
#define glGetBooleani_v (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLboolean*>(264))
#define glGetBooleanv (fg::gl::getGlFuncPtr<void,GLenum,GLboolean*>(265))
#define glGetBufferParameteri64v (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint64*>(266))
#define glGetBufferParameteriv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(267))
#define glGetBufferParameterivARB (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(268))
#define glGetBufferPointerv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLvoid**>(269))
#define glGetBufferPointervARB (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLvoid**>(270))
#define glGetBufferSubData (fg::gl::getGlFuncPtr<void,GLenum,GLintptr,GLsizeiptr,GLvoid*>(271))
#define glGetBufferSubDataARB (fg::gl::getGlFuncPtr<void,GLenum,GLintptrARB,GLsizeiptrARB,GLvoid*>(272))
#define glGetClipPlane (fg::gl::getGlFuncPtr<void,GLenum,GLdouble*>(273))
#define glGetCompressedTexImage (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLvoid*>(274))
#define glGetDoublei_v (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLdouble*>(275))
#define glGetDoublev (fg::gl::getGlFuncPtr<void,GLenum,GLdouble*>(276))
#define glGetError (fg::gl::getGlFuncPtr<GLenum>(277))
#define glGetFloati_v (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLfloat*>(278))
#define glGetFloatv (fg::gl::getGlFuncPtr<void,GLenum,GLfloat*>(279))
#define glGetFragDataIndex (fg::gl::getGlFuncPtr<GLint,GLuint,const GLchar*>(280))
#define glGetFragDataLocation (fg::gl::getGlFuncPtr<GLint,GLuint,const GLchar*>(281))
#define glGetFramebufferAttachmentParameteriv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLint*>(282))
#define glGetFramebufferAttachmentParameterivEXT (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLint*>(283))
#define glGetHandleARB (fg::gl::getGlFuncPtr<GLhandleARB,GLenum>(284))
#define glGetInfoLogARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLsizei,GLsizei*,GLcharARB*>(285))
#define glGetInteger64i_v (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLint64*>(286))
#define glGetInteger64v (fg::gl::getGlFuncPtr<void,GLenum,GLint64*>(287))
#define glGetIntegeri_v (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLint*>(288))
#define glGetIntegerv (fg::gl::getGlFuncPtr<void,GLenum,GLint*>(289))
#define glGetInternalformati64v (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLsizei,GLint64*>(290))
#define glGetLightfv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLfloat*>(291))
#define glGetLightiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(292))
#define glGetMapdv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLdouble*>(293))
#define glGetMapfv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLfloat*>(294))
#define glGetMapiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(295))
#define glGetMaterialfv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLfloat*>(296))
#define glGetMaterialiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(297))
#define glGetMultisamplefv (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLfloat*>(298))
#define glGetObjectParameterfvARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLenum,GLfloat*>(299))
#define glGetObjectParameterivARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLenum,GLint*>(300))
#define glGetPixelMapfv (fg::gl::getGlFuncPtr<void,GLenum,GLfloat*>(301))
#define glGetPixelMapuiv (fg::gl::getGlFuncPtr<void,GLenum,GLuint*>(302))
#define glGetPixelMapusv (fg::gl::getGlFuncPtr<void,GLenum,GLushort*>(303))
#define glGetPointerv (fg::gl::getGlFuncPtr<void,GLenum,GLvoid**>(304))
#define glGetPolygonStipple (fg::gl::getGlFuncPtr<void,GLubyte*>(305))
#define glGetProgramBinary (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,GLsizei*,GLenum*,GLvoid*>(306))
#define glGetProgramEnvParameterdvARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLdouble*>(307))
#define glGetProgramEnvParameterfvARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLfloat*>(308))
#define glGetProgramInfoLog (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,GLsizei*,GLchar*>(309))
#define glGetProgramLocalParameterdvARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLdouble*>(310))
#define glGetProgramLocalParameterfvARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLfloat*>(311))
#define glGetProgramPipelineInfoLog (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,GLsizei*,GLchar*>(312))
#define glGetProgramPipelineiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLint*>(313))
#define glGetProgramStageiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLenum,GLint*>(314))
#define glGetProgramStringARB (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLvoid*>(315))
#define glGetProgramiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLint*>(316))
#define glGetProgramivARB (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(317))
#define glGetQueryIndexediv (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLenum,GLint*>(318))
#define glGetQueryObjecti64v (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLint64*>(319))
#define glGetQueryObjectiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLint*>(320))
#define glGetQueryObjectui64v (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLuint64*>(321))
#define glGetQueryObjectuiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLuint*>(322))
#define glGetQueryiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(323))
#define glGetRenderbufferParameteriv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(324))
#define glGetRenderbufferParameterivEXT (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(325))
#define glGetSamplerParameterIiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLint*>(326))
#define glGetSamplerParameterIuiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLuint*>(327))
#define glGetSamplerParameterfv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLfloat*>(328))
#define glGetSamplerParameteriv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLint*>(329))
#define glGetShaderInfoLog (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,GLsizei*,GLchar*>(330))
#define glGetShaderPrecisionFormat (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*,GLint*>(331))
#define glGetShaderSource (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,GLsizei*,GLchar*>(332))
#define glGetShaderSourceARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLsizei,GLsizei*,GLcharARB*>(333))
#define glGetShaderiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLint*>(334))
#define glGetString (fg::gl::getGlFuncPtr<const GLubyte*,GLenum>(335))
#define glGetStringi (fg::gl::getGlFuncPtr<const GLubyte*,GLenum,GLuint>(336))
#define glGetSubroutineIndex (fg::gl::getGlFuncPtr<GLuint,GLuint,GLenum,const GLchar*>(337))
#define glGetSubroutineUniformLocation (fg::gl::getGlFuncPtr<GLint,GLuint,GLenum,const GLchar*>(338))
#define glGetSynciv (fg::gl::getGlFuncPtr<void,GLsync,GLenum,GLsizei,GLsizei*,GLint*>(339))
#define glGetTexEnvfv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLfloat*>(340))
#define glGetTexEnviv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(341))
#define glGetTexGendv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLdouble*>(342))
#define glGetTexGenfv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLfloat*>(343))
#define glGetTexGeniv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(344))
#define glGetTexImage (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLenum,GLenum,GLvoid*>(345))
#define glGetTexLevelParameterfv (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLenum,GLfloat*>(346))
#define glGetTexLevelParameteriv (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLenum,GLint*>(347))
#define glGetTexParameterIiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(348))
#define glGetTexParameterIuiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLuint*>(349))
#define glGetTexParameterfv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLfloat*>(350))
#define glGetTexParameteriv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint*>(351))
#define glGetTransformFeedbackVarying (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLsizei,GLsizei*,GLsizei*,GLenum*,GLchar*>(352))
#define glGetUniformBlockIndex (fg::gl::getGlFuncPtr<GLuint,GLuint,const GLchar*>(353))
#define glGetUniformIndices (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,const GLchar*const*,GLuint*>(354))
#define glGetUniformLocation (fg::gl::getGlFuncPtr<GLint,GLuint,const GLchar*>(355))
#define glGetUniformLocationARB (fg::gl::getGlFuncPtr<GLint,GLhandleARB,const GLcharARB*>(356))
#define glGetUniformSubroutineuiv (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLuint*>(357))
#define glGetUniformdv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLdouble*>(358))
#define glGetUniformfv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLfloat*>(359))
#define glGetUniformfvARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLint,GLfloat*>(360))
#define glGetUniformiv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLint*>(361))
#define glGetUniformivARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLint,GLint*>(362))
#define glGetUniformuiv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLuint*>(363))
#define glGetVertexAttribIiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLint*>(364))
#define glGetVertexAttribIuiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLuint*>(365))
#define glGetVertexAttribLdv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLdouble*>(366))
#define glGetVertexAttribPointerv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLvoid**>(367))
#define glGetVertexAttribPointervARB (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLvoid**>(368))
#define glGetVertexAttribdv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLdouble*>(369))
#define glGetVertexAttribdvARB (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLdouble*>(370))
#define glGetVertexAttribfv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLfloat*>(371))
#define glGetVertexAttribfvARB (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLfloat*>(372))
#define glGetVertexAttribiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLint*>(373))
#define glGetVertexAttribivARB (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLint*>(374))
#define glHint (fg::gl::getGlFuncPtr<void,GLenum,GLenum>(375))
#define glIndexMask (fg::gl::getGlFuncPtr<void,GLuint>(376))
#define glIndexPointer (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,const GLvoid*>(377))
#define glIndexd (fg::gl::getGlFuncPtr<void,GLdouble>(378))
#define glIndexdv (fg::gl::getGlFuncPtr<void,const GLdouble*>(379))
#define glIndexf (fg::gl::getGlFuncPtr<void,GLfloat>(380))
#define glIndexfv (fg::gl::getGlFuncPtr<void,const GLfloat*>(381))
#define glIndexi (fg::gl::getGlFuncPtr<void,GLint>(382))
#define glIndexiv (fg::gl::getGlFuncPtr<void,const GLint*>(383))
#define glIndexs (fg::gl::getGlFuncPtr<void,GLshort>(384))
#define glIndexsv (fg::gl::getGlFuncPtr<void,const GLshort*>(385))
#define glIndexub (fg::gl::getGlFuncPtr<void,GLubyte>(386))
#define glIndexubv (fg::gl::getGlFuncPtr<void,const GLubyte*>(387))
#define glInitNames (fg::gl::getGlFuncPtr<void>(388))
#define glInterleavedArrays (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,const GLvoid*>(389))
#define glIsBuffer (fg::gl::getGlFuncPtr<GLboolean,GLuint>(390))
#define glIsBufferARB (fg::gl::getGlFuncPtr<GLboolean,GLuint>(391))
#define glIsEnabled (fg::gl::getGlFuncPtr<GLboolean,GLenum>(392))
#define glIsEnabledi (fg::gl::getGlFuncPtr<GLboolean,GLenum,GLuint>(393))
#define glIsFramebuffer (fg::gl::getGlFuncPtr<GLboolean,GLuint>(394))
#define glIsFramebufferEXT (fg::gl::getGlFuncPtr<GLboolean,GLuint>(395))
#define glIsList (fg::gl::getGlFuncPtr<GLboolean,GLuint>(396))
#define glIsProgram (fg::gl::getGlFuncPtr<GLboolean,GLuint>(397))
#define glIsProgramARB (fg::gl::getGlFuncPtr<GLboolean,GLuint>(398))
#define glIsProgramPipeline (fg::gl::getGlFuncPtr<GLboolean,GLuint>(399))
#define glIsQuery (fg::gl::getGlFuncPtr<GLboolean,GLuint>(400))
#define glIsRenderbuffer (fg::gl::getGlFuncPtr<GLboolean,GLuint>(401))
#define glIsRenderbufferEXT (fg::gl::getGlFuncPtr<GLboolean,GLuint>(402))
#define glIsSampler (fg::gl::getGlFuncPtr<GLboolean,GLuint>(403))
#define glIsShader (fg::gl::getGlFuncPtr<GLboolean,GLuint>(404))
#define glIsSync (fg::gl::getGlFuncPtr<GLboolean,GLsync>(405))
#define glIsTexture (fg::gl::getGlFuncPtr<GLboolean,GLuint>(406))
#define glIsTransformFeedback (fg::gl::getGlFuncPtr<GLboolean,GLuint>(407))
#define glIsVertexArray (fg::gl::getGlFuncPtr<GLboolean,GLuint>(408))
#define glLightModelf (fg::gl::getGlFuncPtr<void,GLenum,GLfloat>(409))
#define glLightModelfv (fg::gl::getGlFuncPtr<void,GLenum,const GLfloat*>(410))
#define glLightModeli (fg::gl::getGlFuncPtr<void,GLenum,GLint>(411))
#define glLightModeliv (fg::gl::getGlFuncPtr<void,GLenum,const GLint*>(412))
#define glLightf (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLfloat>(413))
#define glLightfv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLfloat*>(414))
#define glLighti (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint>(415))
#define glLightiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLint*>(416))
#define glLineStipple (fg::gl::getGlFuncPtr<void,GLint,GLushort>(417))
#define glLineWidth (fg::gl::getGlFuncPtr<void,GLfloat>(418))
#define glLinkProgram (fg::gl::getGlFuncPtr<void,GLuint>(419))
#define glLinkProgramARB (fg::gl::getGlFuncPtr<void,GLhandleARB>(420))
#define glListBase (fg::gl::getGlFuncPtr<void,GLuint>(421))
#define glLoadIdentity (fg::gl::getGlFuncPtr<void>(422))
#define glLoadMatrixd (fg::gl::getGlFuncPtr<void,const GLdouble*>(423))
#define glLoadMatrixf (fg::gl::getGlFuncPtr<void,const GLfloat*>(424))
#define glLoadName (fg::gl::getGlFuncPtr<void,GLuint>(425))
#define glLoadTransposeMatrixd (fg::gl::getGlFuncPtr<void,const GLdouble*>(426))
#define glLoadTransposeMatrixf (fg::gl::getGlFuncPtr<void,const GLfloat*>(427))
#define glLogicOp (fg::gl::getGlFuncPtr<void,GLenum>(428))
#define glMap1d (fg::gl::getGlFuncPtr<void,GLenum,GLdouble,GLdouble,GLint,GLint,const GLdouble*>(429))
#define glMap1f (fg::gl::getGlFuncPtr<void,GLenum,GLfloat,GLfloat,GLint,GLint,const GLfloat*>(430))
#define glMap2d (fg::gl::getGlFuncPtr<void,GLenum,GLdouble,GLdouble,GLint,GLint,GLdouble,GLdouble,GLint,GLint,const GLdouble*>(431))
#define glMap2f (fg::gl::getGlFuncPtr<void,GLenum,GLfloat,GLfloat,GLint,GLint,GLfloat,GLfloat,GLint,GLint,const GLfloat*>(432))
#define glMapBuffer (fg::gl::getGlFuncPtr<void *,GLenum,GLenum>(433))
#define glMapBufferARB (fg::gl::getGlFuncPtr<void *,GLenum,GLenum>(434))
#define glMapBufferRange (fg::gl::getGlFuncPtr<void *,GLenum,GLintptr,GLsizeiptr,GLbitfield>(435))
#define glMapGrid1d (fg::gl::getGlFuncPtr<void,GLint,GLdouble,GLdouble>(436))
#define glMapGrid1f (fg::gl::getGlFuncPtr<void,GLint,GLfloat,GLfloat>(437))
#define glMapGrid2d (fg::gl::getGlFuncPtr<void,GLint,GLdouble,GLdouble,GLint,GLdouble,GLdouble>(438))
#define glMapGrid2f (fg::gl::getGlFuncPtr<void,GLint,GLfloat,GLfloat,GLint,GLfloat,GLfloat>(439))
#define glMaterialf (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLfloat>(440))
#define glMaterialfv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLfloat*>(441))
#define glMateriali (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint>(442))
#define glMaterialiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLint*>(443))
#define glMatrixMode (fg::gl::getGlFuncPtr<void,GLenum>(444))
#define glMemoryBarrier (fg::gl::getGlFuncPtr<void,GLbitfield>(445))
#define glMinSampleShading (fg::gl::getGlFuncPtr<void,GLfloat>(446))
#define glMultMatrixd (fg::gl::getGlFuncPtr<void,const GLdouble*>(447))
#define glMultMatrixf (fg::gl::getGlFuncPtr<void,const GLfloat*>(448))
#define glMultTransposeMatrixd (fg::gl::getGlFuncPtr<void,const GLdouble*>(449))
#define glMultTransposeMatrixf (fg::gl::getGlFuncPtr<void,const GLfloat*>(450))
#define glMultiDrawArrays (fg::gl::getGlFuncPtr<void,GLenum,const GLint*,const GLsizei*,GLsizei>(451))
#define glMultiDrawElements (fg::gl::getGlFuncPtr<void,GLenum,const GLsizei*,GLenum,const GLvoid*const*,GLsizei>(452))
#define glMultiDrawElementsBaseVertex (fg::gl::getGlFuncPtr<void,GLenum,const GLsizei*,GLenum,const GLvoid*const*,GLsizei,const GLint*>(453))
#define glMultiTexCoord1d (fg::gl::getGlFuncPtr<void,GLenum,GLdouble>(454))
#define glMultiTexCoord1dv (fg::gl::getGlFuncPtr<void,GLenum,const GLdouble*>(455))
#define glMultiTexCoord1f (fg::gl::getGlFuncPtr<void,GLenum,GLfloat>(456))
#define glMultiTexCoord1fv (fg::gl::getGlFuncPtr<void,GLenum,const GLfloat*>(457))
#define glMultiTexCoord1i (fg::gl::getGlFuncPtr<void,GLenum,GLint>(458))
#define glMultiTexCoord1iv (fg::gl::getGlFuncPtr<void,GLenum,const GLint*>(459))
#define glMultiTexCoord1s (fg::gl::getGlFuncPtr<void,GLenum,GLshort>(460))
#define glMultiTexCoord1sv (fg::gl::getGlFuncPtr<void,GLenum,const GLshort*>(461))
#define glMultiTexCoord2d (fg::gl::getGlFuncPtr<void,GLenum,GLdouble,GLdouble>(462))
#define glMultiTexCoord2dv (fg::gl::getGlFuncPtr<void,GLenum,const GLdouble*>(463))
#define glMultiTexCoord2f (fg::gl::getGlFuncPtr<void,GLenum,GLfloat,GLfloat>(464))
#define glMultiTexCoord2fv (fg::gl::getGlFuncPtr<void,GLenum,const GLfloat*>(465))
#define glMultiTexCoord2i (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint>(466))
#define glMultiTexCoord2iv (fg::gl::getGlFuncPtr<void,GLenum,const GLint*>(467))
#define glMultiTexCoord2s (fg::gl::getGlFuncPtr<void,GLenum,GLshort,GLshort>(468))
#define glMultiTexCoord2sv (fg::gl::getGlFuncPtr<void,GLenum,const GLshort*>(469))
#define glMultiTexCoord3d (fg::gl::getGlFuncPtr<void,GLenum,GLdouble,GLdouble,GLdouble>(470))
#define glMultiTexCoord3dv (fg::gl::getGlFuncPtr<void,GLenum,const GLdouble*>(471))
#define glMultiTexCoord3f (fg::gl::getGlFuncPtr<void,GLenum,GLfloat,GLfloat,GLfloat>(472))
#define glMultiTexCoord3fv (fg::gl::getGlFuncPtr<void,GLenum,const GLfloat*>(473))
#define glMultiTexCoord3i (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLint>(474))
#define glMultiTexCoord3iv (fg::gl::getGlFuncPtr<void,GLenum,const GLint*>(475))
#define glMultiTexCoord3s (fg::gl::getGlFuncPtr<void,GLenum,GLshort,GLshort,GLshort>(476))
#define glMultiTexCoord3sv (fg::gl::getGlFuncPtr<void,GLenum,const GLshort*>(477))
#define glMultiTexCoord4d (fg::gl::getGlFuncPtr<void,GLenum,GLdouble,GLdouble,GLdouble,GLdouble>(478))
#define glMultiTexCoord4dv (fg::gl::getGlFuncPtr<void,GLenum,const GLdouble*>(479))
#define glMultiTexCoord4f (fg::gl::getGlFuncPtr<void,GLenum,GLfloat,GLfloat,GLfloat,GLfloat>(480))
#define glMultiTexCoord4fv (fg::gl::getGlFuncPtr<void,GLenum,const GLfloat*>(481))
#define glMultiTexCoord4i (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLint,GLint>(482))
#define glMultiTexCoord4iv (fg::gl::getGlFuncPtr<void,GLenum,const GLint*>(483))
#define glMultiTexCoord4s (fg::gl::getGlFuncPtr<void,GLenum,GLshort,GLshort,GLshort,GLshort>(484))
#define glMultiTexCoord4sv (fg::gl::getGlFuncPtr<void,GLenum,const GLshort*>(485))
#define glMultiTexCoordP1ui (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLuint>(486))
#define glMultiTexCoordP1uiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLuint*>(487))
#define glMultiTexCoordP2ui (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLuint>(488))
#define glMultiTexCoordP2uiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLuint*>(489))
#define glMultiTexCoordP3ui (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLuint>(490))
#define glMultiTexCoordP3uiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLuint*>(491))
#define glMultiTexCoordP4ui (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLuint>(492))
#define glMultiTexCoordP4uiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLuint*>(493))
#define glNewList (fg::gl::getGlFuncPtr<void,GLuint,GLenum>(494))
#define glNormal3b (fg::gl::getGlFuncPtr<void,GLbyte,GLbyte,GLbyte>(495))
#define glNormal3bv (fg::gl::getGlFuncPtr<void,const GLbyte*>(496))
#define glNormal3d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble>(497))
#define glNormal3dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(498))
#define glNormal3f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat>(499))
#define glNormal3fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(500))
#define glNormal3i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint>(501))
#define glNormal3iv (fg::gl::getGlFuncPtr<void,const GLint*>(502))
#define glNormal3s (fg::gl::getGlFuncPtr<void,GLshort,GLshort,GLshort>(503))
#define glNormal3sv (fg::gl::getGlFuncPtr<void,const GLshort*>(504))
#define glNormalP3ui (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(505))
#define glNormalP3uiv (fg::gl::getGlFuncPtr<void,GLenum,const GLuint*>(506))
#define glNormalPointer (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,const GLvoid*>(507))
#define glOrtho (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble,GLdouble,GLdouble,GLdouble>(508))
#define glPassThrough (fg::gl::getGlFuncPtr<void,GLfloat>(509))
#define glPatchParameterfv (fg::gl::getGlFuncPtr<void,GLenum,const GLfloat*>(510))
#define glPatchParameteri (fg::gl::getGlFuncPtr<void,GLenum,GLint>(511))
#define glPauseTransformFeedback (fg::gl::getGlFuncPtr<void>(512))
#define glPixelMapfv (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,const GLfloat*>(513))
#define glPixelMapuiv (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,const GLuint*>(514))
#define glPixelMapusv (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,const GLushort*>(515))
#define glPixelStoref (fg::gl::getGlFuncPtr<void,GLenum,GLfloat>(516))
#define glPixelStorei (fg::gl::getGlFuncPtr<void,GLenum,GLint>(517))
#define glPixelTransferf (fg::gl::getGlFuncPtr<void,GLenum,GLfloat>(518))
#define glPixelTransferi (fg::gl::getGlFuncPtr<void,GLenum,GLint>(519))
#define glPixelZoom (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat>(520))
#define glPointParameterf (fg::gl::getGlFuncPtr<void,GLenum,GLfloat>(521))
#define glPointParameterfv (fg::gl::getGlFuncPtr<void,GLenum,const GLfloat*>(522))
#define glPointParameteri (fg::gl::getGlFuncPtr<void,GLenum,GLint>(523))
#define glPointParameteriv (fg::gl::getGlFuncPtr<void,GLenum,const GLint*>(524))
#define glPointSize (fg::gl::getGlFuncPtr<void,GLfloat>(525))
#define glPolygonMode (fg::gl::getGlFuncPtr<void,GLenum,GLenum>(526))
#define glPolygonOffset (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat>(527))
#define glPolygonStipple (fg::gl::getGlFuncPtr<void,const GLubyte*>(528))
#define glPopAttrib (fg::gl::getGlFuncPtr<void>(529))
#define glPopClientAttrib (fg::gl::getGlFuncPtr<void>(530))
#define glPopMatrix (fg::gl::getGlFuncPtr<void>(531))
#define glPopName (fg::gl::getGlFuncPtr<void>(532))
#define glPrimitiveRestartIndex (fg::gl::getGlFuncPtr<void,GLuint>(533))
#define glPrioritizeTextures (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*,const GLfloat*>(534))
#define glProgramBinary (fg::gl::getGlFuncPtr<void,GLuint,GLenum,const GLvoid*,GLsizei>(535))
#define glProgramEnvParameter4dARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLdouble,GLdouble,GLdouble,GLdouble>(536))
#define glProgramEnvParameter4dvARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint,const GLdouble*>(537))
#define glProgramEnvParameter4fARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLfloat,GLfloat,GLfloat,GLfloat>(538))
#define glProgramEnvParameter4fvARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint,const GLfloat*>(539))
#define glProgramLocalParameter4dARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLdouble,GLdouble,GLdouble,GLdouble>(540))
#define glProgramLocalParameter4dvARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint,const GLdouble*>(541))
#define glProgramLocalParameter4fARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint,GLfloat,GLfloat,GLfloat,GLfloat>(542))
#define glProgramLocalParameter4fvARB (fg::gl::getGlFuncPtr<void,GLenum,GLuint,const GLfloat*>(543))
#define glProgramParameteri (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLint>(544))
#define glProgramStringARB (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLsizei,const GLvoid*>(545))
#define glProgramUniform1d (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLdouble>(546))
#define glProgramUniform1dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLdouble*>(547))
#define glProgramUniform1f (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLfloat>(548))
#define glProgramUniform1fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLfloat*>(549))
#define glProgramUniform1i (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLint>(550))
#define glProgramUniform1iv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLint*>(551))
#define glProgramUniform1ui (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLuint>(552))
#define glProgramUniform1uiv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLuint*>(553))
#define glProgramUniform2d (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLdouble,GLdouble>(554))
#define glProgramUniform2dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLdouble*>(555))
#define glProgramUniform2f (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLfloat,GLfloat>(556))
#define glProgramUniform2fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLfloat*>(557))
#define glProgramUniform2i (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLint,GLint>(558))
#define glProgramUniform2iv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLint*>(559))
#define glProgramUniform2ui (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLuint,GLuint>(560))
#define glProgramUniform2uiv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLuint*>(561))
#define glProgramUniform3d (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLdouble,GLdouble,GLdouble>(562))
#define glProgramUniform3dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLdouble*>(563))
#define glProgramUniform3f (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLfloat,GLfloat,GLfloat>(564))
#define glProgramUniform3fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLfloat*>(565))
#define glProgramUniform3i (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLint,GLint,GLint>(566))
#define glProgramUniform3iv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLint*>(567))
#define glProgramUniform3ui (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLuint,GLuint,GLuint>(568))
#define glProgramUniform3uiv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLuint*>(569))
#define glProgramUniform4d (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLdouble,GLdouble,GLdouble,GLdouble>(570))
#define glProgramUniform4dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLdouble*>(571))
#define glProgramUniform4f (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLfloat,GLfloat,GLfloat,GLfloat>(572))
#define glProgramUniform4fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLfloat*>(573))
#define glProgramUniform4i (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLint,GLint,GLint,GLint>(574))
#define glProgramUniform4iv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLint*>(575))
#define glProgramUniform4ui (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLuint,GLuint,GLuint,GLuint>(576))
#define glProgramUniform4uiv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,const GLuint*>(577))
#define glProgramUniformMatrix2dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLdouble*>(578))
#define glProgramUniformMatrix2fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLfloat*>(579))
#define glProgramUniformMatrix2x3dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLdouble*>(580))
#define glProgramUniformMatrix2x3fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLfloat*>(581))
#define glProgramUniformMatrix2x4dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLdouble*>(582))
#define glProgramUniformMatrix2x4fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLfloat*>(583))
#define glProgramUniformMatrix3dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLdouble*>(584))
#define glProgramUniformMatrix3fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLfloat*>(585))
#define glProgramUniformMatrix3x2dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLdouble*>(586))
#define glProgramUniformMatrix3x2fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLfloat*>(587))
#define glProgramUniformMatrix3x4dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLdouble*>(588))
#define glProgramUniformMatrix3x4fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLfloat*>(589))
#define glProgramUniformMatrix4dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLdouble*>(590))
#define glProgramUniformMatrix4fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLfloat*>(591))
#define glProgramUniformMatrix4x2dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLdouble*>(592))
#define glProgramUniformMatrix4x2fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLfloat*>(593))
#define glProgramUniformMatrix4x3dv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLdouble*>(594))
#define glProgramUniformMatrix4x3fv (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLsizei,GLboolean,const GLfloat*>(595))
#define glProvokingVertex (fg::gl::getGlFuncPtr<void,GLenum>(596))
#define glPushAttrib (fg::gl::getGlFuncPtr<void,GLbitfield>(597))
#define glPushClientAttrib (fg::gl::getGlFuncPtr<void,GLbitfield>(598))
#define glPushMatrix (fg::gl::getGlFuncPtr<void>(599))
#define glPushName (fg::gl::getGlFuncPtr<void,GLuint>(600))
#define glQueryCounter (fg::gl::getGlFuncPtr<void,GLuint,GLenum>(601))
#define glRasterPos2d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble>(602))
#define glRasterPos2dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(603))
#define glRasterPos2f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat>(604))
#define glRasterPos2fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(605))
#define glRasterPos2i (fg::gl::getGlFuncPtr<void,GLint,GLint>(606))
#define glRasterPos2iv (fg::gl::getGlFuncPtr<void,const GLint*>(607))
#define glRasterPos2s (fg::gl::getGlFuncPtr<void,GLshort,GLshort>(608))
#define glRasterPos2sv (fg::gl::getGlFuncPtr<void,const GLshort*>(609))
#define glRasterPos3d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble>(610))
#define glRasterPos3dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(611))
#define glRasterPos3f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat>(612))
#define glRasterPos3fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(613))
#define glRasterPos3i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint>(614))
#define glRasterPos3iv (fg::gl::getGlFuncPtr<void,const GLint*>(615))
#define glRasterPos3s (fg::gl::getGlFuncPtr<void,GLshort,GLshort,GLshort>(616))
#define glRasterPos3sv (fg::gl::getGlFuncPtr<void,const GLshort*>(617))
#define glRasterPos4d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble,GLdouble>(618))
#define glRasterPos4dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(619))
#define glRasterPos4f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat,GLfloat>(620))
#define glRasterPos4fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(621))
#define glRasterPos4i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint,GLint>(622))
#define glRasterPos4iv (fg::gl::getGlFuncPtr<void,const GLint*>(623))
#define glRasterPos4s (fg::gl::getGlFuncPtr<void,GLshort,GLshort,GLshort,GLshort>(624))
#define glRasterPos4sv (fg::gl::getGlFuncPtr<void,const GLshort*>(625))
#define glReadBuffer (fg::gl::getGlFuncPtr<void,GLenum>(626))
#define glReadPixels (fg::gl::getGlFuncPtr<void,GLint,GLint,GLsizei,GLsizei,GLenum,GLenum,GLvoid*>(627))
#define glRectd (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble,GLdouble>(628))
#define glRectdv (fg::gl::getGlFuncPtr<void,const GLdouble*,const GLdouble*>(629))
#define glRectf (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat,GLfloat>(630))
#define glRectfv (fg::gl::getGlFuncPtr<void,const GLfloat*,const GLfloat*>(631))
#define glRecti (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint,GLint>(632))
#define glRectiv (fg::gl::getGlFuncPtr<void,const GLint*,const GLint*>(633))
#define glRects (fg::gl::getGlFuncPtr<void,GLshort,GLshort,GLshort,GLshort>(634))
#define glRectsv (fg::gl::getGlFuncPtr<void,const GLshort*,const GLshort*>(635))
#define glReleaseShaderCompiler (fg::gl::getGlFuncPtr<void>(636))
#define glRenderMode (fg::gl::getGlFuncPtr<GLint,GLenum>(637))
#define glRenderbufferStorage (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLsizei,GLsizei>(638))
#define glRenderbufferStorageEXT (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLsizei,GLsizei>(639))
#define glRenderbufferStorageMultisample (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,GLenum,GLsizei,GLsizei>(640))
#define glResumeTransformFeedback (fg::gl::getGlFuncPtr<void>(641))
#define glRotated (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble,GLdouble>(642))
#define glRotatef (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat,GLfloat>(643))
#define glSampleCoverage (fg::gl::getGlFuncPtr<void,GLfloat,GLboolean>(644))
#define glSampleMaski (fg::gl::getGlFuncPtr<void,GLuint,GLbitfield>(645))
#define glSamplerParameterIiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,const GLint*>(646))
#define glSamplerParameterIuiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,const GLuint*>(647))
#define glSamplerParameterf (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLfloat>(648))
#define glSamplerParameterfv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,const GLfloat*>(649))
#define glSamplerParameteri (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLint>(650))
#define glSamplerParameteriv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,const GLint*>(651))
#define glScaled (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble>(652))
#define glScalef (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat>(653))
#define glScissor (fg::gl::getGlFuncPtr<void,GLint,GLint,GLsizei,GLsizei>(654))
#define glScissorArrayv (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,const GLint*>(655))
#define glScissorIndexed (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLint,GLsizei,GLsizei>(656))
#define glScissorIndexedv (fg::gl::getGlFuncPtr<void,GLuint,const GLint*>(657))
#define glSecondaryColor3b (fg::gl::getGlFuncPtr<void,GLbyte,GLbyte,GLbyte>(658))
#define glSecondaryColor3bv (fg::gl::getGlFuncPtr<void,const GLbyte*>(659))
#define glSecondaryColor3d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble>(660))
#define glSecondaryColor3dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(661))
#define glSecondaryColor3f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat>(662))
#define glSecondaryColor3fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(663))
#define glSecondaryColor3i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint>(664))
#define glSecondaryColor3iv (fg::gl::getGlFuncPtr<void,const GLint*>(665))
#define glSecondaryColor3s (fg::gl::getGlFuncPtr<void,GLshort,GLshort,GLshort>(666))
#define glSecondaryColor3sv (fg::gl::getGlFuncPtr<void,const GLshort*>(667))
#define glSecondaryColor3ub (fg::gl::getGlFuncPtr<void,GLubyte,GLubyte,GLubyte>(668))
#define glSecondaryColor3ubv (fg::gl::getGlFuncPtr<void,const GLubyte*>(669))
#define glSecondaryColor3ui (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLuint>(670))
#define glSecondaryColor3uiv (fg::gl::getGlFuncPtr<void,const GLuint*>(671))
#define glSecondaryColor3us (fg::gl::getGlFuncPtr<void,GLushort,GLushort,GLushort>(672))
#define glSecondaryColor3usv (fg::gl::getGlFuncPtr<void,const GLushort*>(673))
#define glSecondaryColorP3ui (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(674))
#define glSecondaryColorP3uiv (fg::gl::getGlFuncPtr<void,GLenum,const GLuint*>(675))
#define glSecondaryColorPointer (fg::gl::getGlFuncPtr<void,GLint,GLenum,GLsizei,const GLvoid*>(676))
#define glSelectBuffer (fg::gl::getGlFuncPtr<void,GLsizei,GLuint*>(677))
#define glShadeModel (fg::gl::getGlFuncPtr<void,GLenum>(678))
#define glShaderBinary (fg::gl::getGlFuncPtr<void,GLsizei,const GLuint*,GLenum,const GLvoid*,GLsizei>(679))
#define glShaderSource (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,const GLchar*const*,const GLint*>(680))
#define glShaderSourceARB (fg::gl::getGlFuncPtr<void,GLhandleARB,GLsizei,const GLcharARB**,const GLint*>(681))
#define glStencilFunc (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLuint>(682))
#define glStencilFuncSeparate (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint,GLuint>(683))
#define glStencilMask (fg::gl::getGlFuncPtr<void,GLuint>(684))
#define glStencilMaskSeparate (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(685))
#define glStencilOp (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum>(686))
#define glStencilOpSeparate (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLenum,GLenum>(687))
#define glTexBuffer (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLuint>(688))
#define glTexCoord1d (fg::gl::getGlFuncPtr<void,GLdouble>(689))
#define glTexCoord1dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(690))
#define glTexCoord1f (fg::gl::getGlFuncPtr<void,GLfloat>(691))
#define glTexCoord1fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(692))
#define glTexCoord1i (fg::gl::getGlFuncPtr<void,GLint>(693))
#define glTexCoord1iv (fg::gl::getGlFuncPtr<void,const GLint*>(694))
#define glTexCoord1s (fg::gl::getGlFuncPtr<void,GLshort>(695))
#define glTexCoord1sv (fg::gl::getGlFuncPtr<void,const GLshort*>(696))
#define glTexCoord2d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble>(697))
#define glTexCoord2dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(698))
#define glTexCoord2f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat>(699))
#define glTexCoord2fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(700))
#define glTexCoord2i (fg::gl::getGlFuncPtr<void,GLint,GLint>(701))
#define glTexCoord2iv (fg::gl::getGlFuncPtr<void,const GLint*>(702))
#define glTexCoord2s (fg::gl::getGlFuncPtr<void,GLshort,GLshort>(703))
#define glTexCoord2sv (fg::gl::getGlFuncPtr<void,const GLshort*>(704))
#define glTexCoord3d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble>(705))
#define glTexCoord3dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(706))
#define glTexCoord3f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat>(707))
#define glTexCoord3fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(708))
#define glTexCoord3i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint>(709))
#define glTexCoord3iv (fg::gl::getGlFuncPtr<void,const GLint*>(710))
#define glTexCoord3s (fg::gl::getGlFuncPtr<void,GLshort,GLshort,GLshort>(711))
#define glTexCoord3sv (fg::gl::getGlFuncPtr<void,const GLshort*>(712))
#define glTexCoord4d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble,GLdouble>(713))
#define glTexCoord4dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(714))
#define glTexCoord4f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat,GLfloat>(715))
#define glTexCoord4fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(716))
#define glTexCoord4i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint,GLint>(717))
#define glTexCoord4iv (fg::gl::getGlFuncPtr<void,const GLint*>(718))
#define glTexCoord4s (fg::gl::getGlFuncPtr<void,GLshort,GLshort,GLshort,GLshort>(719))
#define glTexCoord4sv (fg::gl::getGlFuncPtr<void,const GLshort*>(720))
#define glTexCoordP1ui (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(721))
#define glTexCoordP1uiv (fg::gl::getGlFuncPtr<void,GLenum,const GLuint*>(722))
#define glTexCoordP2ui (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(723))
#define glTexCoordP2uiv (fg::gl::getGlFuncPtr<void,GLenum,const GLuint*>(724))
#define glTexCoordP3ui (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(725))
#define glTexCoordP3uiv (fg::gl::getGlFuncPtr<void,GLenum,const GLuint*>(726))
#define glTexCoordP4ui (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(727))
#define glTexCoordP4uiv (fg::gl::getGlFuncPtr<void,GLenum,const GLuint*>(728))
#define glTexCoordPointer (fg::gl::getGlFuncPtr<void,GLint,GLenum,GLsizei,const GLvoid*>(729))
#define glTexEnvf (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLfloat>(730))
#define glTexEnvfv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLfloat*>(731))
#define glTexEnvi (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint>(732))
#define glTexEnviv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLint*>(733))
#define glTexGend (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLdouble>(734))
#define glTexGendv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLdouble*>(735))
#define glTexGenf (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLfloat>(736))
#define glTexGenfv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLfloat*>(737))
#define glTexGeni (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint>(738))
#define glTexGeniv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLint*>(739))
#define glTexImage1D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLsizei,GLint,GLenum,GLenum,const GLvoid*>(740))
#define glTexImage2D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLsizei,GLsizei,GLint,GLenum,GLenum,const GLvoid*>(741))
#define glTexImage2DMultisample (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,GLint,GLsizei,GLsizei,GLboolean>(742))
#define glTexImage3D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLsizei,GLsizei,GLsizei,GLint,GLenum,GLenum,const GLvoid*>(743))
#define glTexImage3DMultisample (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,GLint,GLsizei,GLsizei,GLsizei,GLboolean>(744))
#define glTexParameterIiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLint*>(745))
#define glTexParameterIuiv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLuint*>(746))
#define glTexParameterf (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLfloat>(747))
#define glTexParameterfv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLfloat*>(748))
#define glTexParameteri (fg::gl::getGlFuncPtr<void,GLenum,GLenum,GLint>(749))
#define glTexParameteriv (fg::gl::getGlFuncPtr<void,GLenum,GLenum,const GLint*>(750))
#define glTexStorage1D (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,GLenum,GLsizei>(751))
#define glTexStorage2D (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,GLenum,GLsizei,GLsizei>(752))
#define glTexStorage3D (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,GLenum,GLsizei,GLsizei,GLsizei>(753))
#define glTexSubImage1D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLsizei,GLenum,GLenum,const GLvoid*>(754))
#define glTexSubImage2D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLint,GLsizei,GLsizei,GLenum,GLenum,const GLvoid*>(755))
#define glTexSubImage3D (fg::gl::getGlFuncPtr<void,GLenum,GLint,GLint,GLint,GLint,GLsizei,GLsizei,GLsizei,GLenum,GLenum,const GLvoid*>(756))
#define glTransformFeedbackVaryings (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,const GLchar*const*,GLenum>(757))
#define glTranslated (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble>(758))
#define glTranslatef (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat>(759))
#define glUniform1d (fg::gl::getGlFuncPtr<void,GLint,GLdouble>(760))
#define glUniform1dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLdouble*>(761))
#define glUniform1f (fg::gl::getGlFuncPtr<void,GLint,GLfloat>(762))
#define glUniform1fARB (fg::gl::getGlFuncPtr<void,GLint,GLfloat>(763))
#define glUniform1fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLfloat*>(764))
#define glUniform1fvARB (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLfloat*>(765))
#define glUniform1i (fg::gl::getGlFuncPtr<void,GLint,GLint>(766))
#define glUniform1iARB (fg::gl::getGlFuncPtr<void,GLint,GLint>(767))
#define glUniform1iv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLint*>(768))
#define glUniform1ivARB (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLint*>(769))
#define glUniform1ui (fg::gl::getGlFuncPtr<void,GLint,GLuint>(770))
#define glUniform1uiv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLuint*>(771))
#define glUniform2d (fg::gl::getGlFuncPtr<void,GLint,GLdouble,GLdouble>(772))
#define glUniform2dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLdouble*>(773))
#define glUniform2f (fg::gl::getGlFuncPtr<void,GLint,GLfloat,GLfloat>(774))
#define glUniform2fARB (fg::gl::getGlFuncPtr<void,GLint,GLfloat,GLfloat>(775))
#define glUniform2fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLfloat*>(776))
#define glUniform2fvARB (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLfloat*>(777))
#define glUniform2i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint>(778))
#define glUniform2iARB (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint>(779))
#define glUniform2iv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLint*>(780))
#define glUniform2ivARB (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLint*>(781))
#define glUniform2ui (fg::gl::getGlFuncPtr<void,GLint,GLuint,GLuint>(782))
#define glUniform2uiv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLuint*>(783))
#define glUniform3d (fg::gl::getGlFuncPtr<void,GLint,GLdouble,GLdouble,GLdouble>(784))
#define glUniform3dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLdouble*>(785))
#define glUniform3f (fg::gl::getGlFuncPtr<void,GLint,GLfloat,GLfloat,GLfloat>(786))
#define glUniform3fARB (fg::gl::getGlFuncPtr<void,GLint,GLfloat,GLfloat,GLfloat>(787))
#define glUniform3fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLfloat*>(788))
#define glUniform3fvARB (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLfloat*>(789))
#define glUniform3i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint,GLint>(790))
#define glUniform3iARB (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint,GLint>(791))
#define glUniform3iv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLint*>(792))
#define glUniform3ivARB (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLint*>(793))
#define glUniform3ui (fg::gl::getGlFuncPtr<void,GLint,GLuint,GLuint,GLuint>(794))
#define glUniform3uiv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLuint*>(795))
#define glUniform4d (fg::gl::getGlFuncPtr<void,GLint,GLdouble,GLdouble,GLdouble,GLdouble>(796))
#define glUniform4dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLdouble*>(797))
#define glUniform4f (fg::gl::getGlFuncPtr<void,GLint,GLfloat,GLfloat,GLfloat,GLfloat>(798))
#define glUniform4fARB (fg::gl::getGlFuncPtr<void,GLint,GLfloat,GLfloat,GLfloat,GLfloat>(799))
#define glUniform4fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLfloat*>(800))
#define glUniform4fvARB (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLfloat*>(801))
#define glUniform4i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint,GLint,GLint>(802))
#define glUniform4iARB (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint,GLint,GLint>(803))
#define glUniform4iv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLint*>(804))
#define glUniform4ivARB (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLint*>(805))
#define glUniform4ui (fg::gl::getGlFuncPtr<void,GLint,GLuint,GLuint,GLuint,GLuint>(806))
#define glUniform4uiv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,const GLuint*>(807))
#define glUniformBlockBinding (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLuint>(808))
#define glUniformMatrix2dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLdouble*>(809))
#define glUniformMatrix2fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLfloat*>(810))
#define glUniformMatrix2fvARB (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLfloat*>(811))
#define glUniformMatrix2x3dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLdouble*>(812))
#define glUniformMatrix2x3fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLfloat*>(813))
#define glUniformMatrix2x4dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLdouble*>(814))
#define glUniformMatrix2x4fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLfloat*>(815))
#define glUniformMatrix3dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLdouble*>(816))
#define glUniformMatrix3fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLfloat*>(817))
#define glUniformMatrix3fvARB (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLfloat*>(818))
#define glUniformMatrix3x2dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLdouble*>(819))
#define glUniformMatrix3x2fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLfloat*>(820))
#define glUniformMatrix3x4dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLdouble*>(821))
#define glUniformMatrix3x4fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLfloat*>(822))
#define glUniformMatrix4dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLdouble*>(823))
#define glUniformMatrix4fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLfloat*>(824))
#define glUniformMatrix4fvARB (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLfloat*>(825))
#define glUniformMatrix4x2dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLdouble*>(826))
#define glUniformMatrix4x2fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLfloat*>(827))
#define glUniformMatrix4x3dv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLdouble*>(828))
#define glUniformMatrix4x3fv (fg::gl::getGlFuncPtr<void,GLint,GLsizei,GLboolean,const GLfloat*>(829))
#define glUniformSubroutinesuiv (fg::gl::getGlFuncPtr<void,GLenum,GLsizei,const GLuint*>(830))
#define glUnmapBuffer (fg::gl::getGlFuncPtr<GLboolean,GLenum>(831))
#define glUnmapBufferARB (fg::gl::getGlFuncPtr<GLboolean,GLenum>(832))
#define glUseProgram (fg::gl::getGlFuncPtr<void,GLuint>(833))
#define glUseProgramObjectARB (fg::gl::getGlFuncPtr<void,GLhandleARB>(834))
#define glUseProgramStages (fg::gl::getGlFuncPtr<void,GLuint,GLbitfield,GLuint>(835))
#define glValidateProgram (fg::gl::getGlFuncPtr<void,GLuint>(836))
#define glValidateProgramARB (fg::gl::getGlFuncPtr<void,GLhandleARB>(837))
#define glValidateProgramPipeline (fg::gl::getGlFuncPtr<void,GLuint>(838))
#define glVertex2d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble>(839))
#define glVertex2dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(840))
#define glVertex2f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat>(841))
#define glVertex2fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(842))
#define glVertex2i (fg::gl::getGlFuncPtr<void,GLint,GLint>(843))
#define glVertex2iv (fg::gl::getGlFuncPtr<void,const GLint*>(844))
#define glVertex2s (fg::gl::getGlFuncPtr<void,GLshort,GLshort>(845))
#define glVertex2sv (fg::gl::getGlFuncPtr<void,const GLshort*>(846))
#define glVertex3d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble>(847))
#define glVertex3dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(848))
#define glVertex3f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat>(849))
#define glVertex3fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(850))
#define glVertex3i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint>(851))
#define glVertex3iv (fg::gl::getGlFuncPtr<void,const GLint*>(852))
#define glVertex3s (fg::gl::getGlFuncPtr<void,GLshort,GLshort,GLshort>(853))
#define glVertex3sv (fg::gl::getGlFuncPtr<void,const GLshort*>(854))
#define glVertex4d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble,GLdouble>(855))
#define glVertex4dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(856))
#define glVertex4f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat,GLfloat>(857))
#define glVertex4fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(858))
#define glVertex4i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint,GLint>(859))
#define glVertex4iv (fg::gl::getGlFuncPtr<void,const GLint*>(860))
#define glVertex4s (fg::gl::getGlFuncPtr<void,GLshort,GLshort,GLshort,GLshort>(861))
#define glVertex4sv (fg::gl::getGlFuncPtr<void,const GLshort*>(862))
#define glVertexAttrib1d (fg::gl::getGlFuncPtr<void,GLuint,GLdouble>(863))
#define glVertexAttrib1dARB (fg::gl::getGlFuncPtr<void,GLuint,GLdouble>(864))
#define glVertexAttrib1dv (fg::gl::getGlFuncPtr<void,GLuint,const GLdouble*>(865))
#define glVertexAttrib1dvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLdouble*>(866))
#define glVertexAttrib1f (fg::gl::getGlFuncPtr<void,GLuint,GLfloat>(867))
#define glVertexAttrib1fARB (fg::gl::getGlFuncPtr<void,GLuint,GLfloat>(868))
#define glVertexAttrib1fv (fg::gl::getGlFuncPtr<void,GLuint,const GLfloat*>(869))
#define glVertexAttrib1fvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLfloat*>(870))
#define glVertexAttrib1s (fg::gl::getGlFuncPtr<void,GLuint,GLshort>(871))
#define glVertexAttrib1sARB (fg::gl::getGlFuncPtr<void,GLuint,GLshort>(872))
#define glVertexAttrib1sv (fg::gl::getGlFuncPtr<void,GLuint,const GLshort*>(873))
#define glVertexAttrib1svARB (fg::gl::getGlFuncPtr<void,GLuint,const GLshort*>(874))
#define glVertexAttrib2d (fg::gl::getGlFuncPtr<void,GLuint,GLdouble,GLdouble>(875))
#define glVertexAttrib2dARB (fg::gl::getGlFuncPtr<void,GLuint,GLdouble,GLdouble>(876))
#define glVertexAttrib2dv (fg::gl::getGlFuncPtr<void,GLuint,const GLdouble*>(877))
#define glVertexAttrib2dvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLdouble*>(878))
#define glVertexAttrib2f (fg::gl::getGlFuncPtr<void,GLuint,GLfloat,GLfloat>(879))
#define glVertexAttrib2fARB (fg::gl::getGlFuncPtr<void,GLuint,GLfloat,GLfloat>(880))
#define glVertexAttrib2fv (fg::gl::getGlFuncPtr<void,GLuint,const GLfloat*>(881))
#define glVertexAttrib2fvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLfloat*>(882))
#define glVertexAttrib2s (fg::gl::getGlFuncPtr<void,GLuint,GLshort,GLshort>(883))
#define glVertexAttrib2sARB (fg::gl::getGlFuncPtr<void,GLuint,GLshort,GLshort>(884))
#define glVertexAttrib2sv (fg::gl::getGlFuncPtr<void,GLuint,const GLshort*>(885))
#define glVertexAttrib2svARB (fg::gl::getGlFuncPtr<void,GLuint,const GLshort*>(886))
#define glVertexAttrib3d (fg::gl::getGlFuncPtr<void,GLuint,GLdouble,GLdouble,GLdouble>(887))
#define glVertexAttrib3dARB (fg::gl::getGlFuncPtr<void,GLuint,GLdouble,GLdouble,GLdouble>(888))
#define glVertexAttrib3dv (fg::gl::getGlFuncPtr<void,GLuint,const GLdouble*>(889))
#define glVertexAttrib3dvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLdouble*>(890))
#define glVertexAttrib3f (fg::gl::getGlFuncPtr<void,GLuint,GLfloat,GLfloat,GLfloat>(891))
#define glVertexAttrib3fARB (fg::gl::getGlFuncPtr<void,GLuint,GLfloat,GLfloat,GLfloat>(892))
#define glVertexAttrib3fv (fg::gl::getGlFuncPtr<void,GLuint,const GLfloat*>(893))
#define glVertexAttrib3fvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLfloat*>(894))
#define glVertexAttrib3s (fg::gl::getGlFuncPtr<void,GLuint,GLshort,GLshort,GLshort>(895))
#define glVertexAttrib3sARB (fg::gl::getGlFuncPtr<void,GLuint,GLshort,GLshort,GLshort>(896))
#define glVertexAttrib3sv (fg::gl::getGlFuncPtr<void,GLuint,const GLshort*>(897))
#define glVertexAttrib3svARB (fg::gl::getGlFuncPtr<void,GLuint,const GLshort*>(898))
#define glVertexAttrib4Nbv (fg::gl::getGlFuncPtr<void,GLuint,const GLbyte*>(899))
#define glVertexAttrib4NbvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLbyte*>(900))
#define glVertexAttrib4Niv (fg::gl::getGlFuncPtr<void,GLuint,const GLint*>(901))
#define glVertexAttrib4NivARB (fg::gl::getGlFuncPtr<void,GLuint,const GLint*>(902))
#define glVertexAttrib4Nsv (fg::gl::getGlFuncPtr<void,GLuint,const GLshort*>(903))
#define glVertexAttrib4NsvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLshort*>(904))
#define glVertexAttrib4Nub (fg::gl::getGlFuncPtr<void,GLuint,GLubyte,GLubyte,GLubyte,GLubyte>(905))
#define glVertexAttrib4NubARB (fg::gl::getGlFuncPtr<void,GLuint,GLubyte,GLubyte,GLubyte,GLubyte>(906))
#define glVertexAttrib4Nubv (fg::gl::getGlFuncPtr<void,GLuint,const GLubyte*>(907))
#define glVertexAttrib4NubvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLubyte*>(908))
#define glVertexAttrib4Nuiv (fg::gl::getGlFuncPtr<void,GLuint,const GLuint*>(909))
#define glVertexAttrib4NuivARB (fg::gl::getGlFuncPtr<void,GLuint,const GLuint*>(910))
#define glVertexAttrib4Nusv (fg::gl::getGlFuncPtr<void,GLuint,const GLushort*>(911))
#define glVertexAttrib4NusvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLushort*>(912))
#define glVertexAttrib4bv (fg::gl::getGlFuncPtr<void,GLuint,const GLbyte*>(913))
#define glVertexAttrib4bvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLbyte*>(914))
#define glVertexAttrib4d (fg::gl::getGlFuncPtr<void,GLuint,GLdouble,GLdouble,GLdouble,GLdouble>(915))
#define glVertexAttrib4dARB (fg::gl::getGlFuncPtr<void,GLuint,GLdouble,GLdouble,GLdouble,GLdouble>(916))
#define glVertexAttrib4dv (fg::gl::getGlFuncPtr<void,GLuint,const GLdouble*>(917))
#define glVertexAttrib4dvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLdouble*>(918))
#define glVertexAttrib4f (fg::gl::getGlFuncPtr<void,GLuint,GLfloat,GLfloat,GLfloat,GLfloat>(919))
#define glVertexAttrib4fARB (fg::gl::getGlFuncPtr<void,GLuint,GLfloat,GLfloat,GLfloat,GLfloat>(920))
#define glVertexAttrib4fv (fg::gl::getGlFuncPtr<void,GLuint,const GLfloat*>(921))
#define glVertexAttrib4fvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLfloat*>(922))
#define glVertexAttrib4iv (fg::gl::getGlFuncPtr<void,GLuint,const GLint*>(923))
#define glVertexAttrib4ivARB (fg::gl::getGlFuncPtr<void,GLuint,const GLint*>(924))
#define glVertexAttrib4s (fg::gl::getGlFuncPtr<void,GLuint,GLshort,GLshort,GLshort,GLshort>(925))
#define glVertexAttrib4sARB (fg::gl::getGlFuncPtr<void,GLuint,GLshort,GLshort,GLshort,GLshort>(926))
#define glVertexAttrib4sv (fg::gl::getGlFuncPtr<void,GLuint,const GLshort*>(927))
#define glVertexAttrib4svARB (fg::gl::getGlFuncPtr<void,GLuint,const GLshort*>(928))
#define glVertexAttrib4ubv (fg::gl::getGlFuncPtr<void,GLuint,const GLubyte*>(929))
#define glVertexAttrib4ubvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLubyte*>(930))
#define glVertexAttrib4uiv (fg::gl::getGlFuncPtr<void,GLuint,const GLuint*>(931))
#define glVertexAttrib4uivARB (fg::gl::getGlFuncPtr<void,GLuint,const GLuint*>(932))
#define glVertexAttrib4usv (fg::gl::getGlFuncPtr<void,GLuint,const GLushort*>(933))
#define glVertexAttrib4usvARB (fg::gl::getGlFuncPtr<void,GLuint,const GLushort*>(934))
#define glVertexAttribDivisor (fg::gl::getGlFuncPtr<void,GLuint,GLuint>(935))
#define glVertexAttribI1i (fg::gl::getGlFuncPtr<void,GLuint,GLint>(936))
#define glVertexAttribI1iv (fg::gl::getGlFuncPtr<void,GLuint,const GLint*>(937))
#define glVertexAttribI1ui (fg::gl::getGlFuncPtr<void,GLuint,GLuint>(938))
#define glVertexAttribI1uiv (fg::gl::getGlFuncPtr<void,GLuint,const GLuint*>(939))
#define glVertexAttribI2i (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLint>(940))
#define glVertexAttribI2iv (fg::gl::getGlFuncPtr<void,GLuint,const GLint*>(941))
#define glVertexAttribI2ui (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLuint>(942))
#define glVertexAttribI2uiv (fg::gl::getGlFuncPtr<void,GLuint,const GLuint*>(943))
#define glVertexAttribI3i (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLint,GLint>(944))
#define glVertexAttribI3iv (fg::gl::getGlFuncPtr<void,GLuint,const GLint*>(945))
#define glVertexAttribI3ui (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLuint,GLuint>(946))
#define glVertexAttribI3uiv (fg::gl::getGlFuncPtr<void,GLuint,const GLuint*>(947))
#define glVertexAttribI4bv (fg::gl::getGlFuncPtr<void,GLuint,const GLbyte*>(948))
#define glVertexAttribI4i (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLint,GLint,GLint>(949))
#define glVertexAttribI4iv (fg::gl::getGlFuncPtr<void,GLuint,const GLint*>(950))
#define glVertexAttribI4sv (fg::gl::getGlFuncPtr<void,GLuint,const GLshort*>(951))
#define glVertexAttribI4ubv (fg::gl::getGlFuncPtr<void,GLuint,const GLubyte*>(952))
#define glVertexAttribI4ui (fg::gl::getGlFuncPtr<void,GLuint,GLuint,GLuint,GLuint,GLuint>(953))
#define glVertexAttribI4uiv (fg::gl::getGlFuncPtr<void,GLuint,const GLuint*>(954))
#define glVertexAttribI4usv (fg::gl::getGlFuncPtr<void,GLuint,const GLushort*>(955))
#define glVertexAttribIPointer (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLenum,GLsizei,const GLvoid*>(956))
#define glVertexAttribL1d (fg::gl::getGlFuncPtr<void,GLuint,GLdouble>(957))
#define glVertexAttribL1dv (fg::gl::getGlFuncPtr<void,GLuint,const GLdouble*>(958))
#define glVertexAttribL2d (fg::gl::getGlFuncPtr<void,GLuint,GLdouble,GLdouble>(959))
#define glVertexAttribL2dv (fg::gl::getGlFuncPtr<void,GLuint,const GLdouble*>(960))
#define glVertexAttribL3d (fg::gl::getGlFuncPtr<void,GLuint,GLdouble,GLdouble,GLdouble>(961))
#define glVertexAttribL3dv (fg::gl::getGlFuncPtr<void,GLuint,const GLdouble*>(962))
#define glVertexAttribL4d (fg::gl::getGlFuncPtr<void,GLuint,GLdouble,GLdouble,GLdouble,GLdouble>(963))
#define glVertexAttribL4dv (fg::gl::getGlFuncPtr<void,GLuint,const GLdouble*>(964))
#define glVertexAttribLPointer (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLenum,GLsizei,const GLvoid*>(965))
#define glVertexAttribP1ui (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLboolean,GLuint>(966))
#define glVertexAttribP1uiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLboolean,const GLuint*>(967))
#define glVertexAttribP2ui (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLboolean,GLuint>(968))
#define glVertexAttribP2uiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLboolean,const GLuint*>(969))
#define glVertexAttribP3ui (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLboolean,GLuint>(970))
#define glVertexAttribP3uiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLboolean,const GLuint*>(971))
#define glVertexAttribP4ui (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLboolean,GLuint>(972))
#define glVertexAttribP4uiv (fg::gl::getGlFuncPtr<void,GLuint,GLenum,GLboolean,const GLuint*>(973))
#define glVertexAttribPointer (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLenum,GLboolean,GLsizei,const GLvoid*>(974))
#define glVertexAttribPointerARB (fg::gl::getGlFuncPtr<void,GLuint,GLint,GLenum,GLboolean,GLsizei,const GLvoid*>(975))
#define glVertexP2ui (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(976))
#define glVertexP2uiv (fg::gl::getGlFuncPtr<void,GLenum,const GLuint*>(977))
#define glVertexP3ui (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(978))
#define glVertexP3uiv (fg::gl::getGlFuncPtr<void,GLenum,const GLuint*>(979))
#define glVertexP4ui (fg::gl::getGlFuncPtr<void,GLenum,GLuint>(980))
#define glVertexP4uiv (fg::gl::getGlFuncPtr<void,GLenum,const GLuint*>(981))
#define glVertexPointer (fg::gl::getGlFuncPtr<void,GLint,GLenum,GLsizei,const GLvoid*>(982))
#define glViewport (fg::gl::getGlFuncPtr<void,GLint,GLint,GLsizei,GLsizei>(983))
#define glViewportArrayv (fg::gl::getGlFuncPtr<void,GLuint,GLsizei,const GLfloat*>(984))
#define glViewportIndexedf (fg::gl::getGlFuncPtr<void,GLuint,GLfloat,GLfloat,GLfloat,GLfloat>(985))
#define glViewportIndexedfv (fg::gl::getGlFuncPtr<void,GLuint,const GLfloat*>(986))
#define glWaitSync (fg::gl::getGlFuncPtr<void,GLsync,GLbitfield,GLuint64>(987))
#define glWindowPos2d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble>(988))
#define glWindowPos2dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(989))
#define glWindowPos2f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat>(990))
#define glWindowPos2fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(991))
#define glWindowPos2i (fg::gl::getGlFuncPtr<void,GLint,GLint>(992))
#define glWindowPos2iv (fg::gl::getGlFuncPtr<void,const GLint*>(993))
#define glWindowPos2s (fg::gl::getGlFuncPtr<void,GLshort,GLshort>(994))
#define glWindowPos2sv (fg::gl::getGlFuncPtr<void,const GLshort*>(995))
#define glWindowPos3d (fg::gl::getGlFuncPtr<void,GLdouble,GLdouble,GLdouble>(996))
#define glWindowPos3dv (fg::gl::getGlFuncPtr<void,const GLdouble*>(997))
#define glWindowPos3f (fg::gl::getGlFuncPtr<void,GLfloat,GLfloat,GLfloat>(998))
#define glWindowPos3fv (fg::gl::getGlFuncPtr<void,const GLfloat*>(999))
#define glWindowPos3i (fg::gl::getGlFuncPtr<void,GLint,GLint,GLint>(1000))
#define glWindowPos3iv (fg::gl::getGlFuncPtr<void,const GLint*>(1001))
#define glWindowPos3s (fg::gl::getGlFuncPtr<void,GLshort,GLshort,GLshort>(1002))

#endif // FRONTIER_GL_FUNCTIONS_H_INCLUDED
